package org.vaadin.addons.logview;

import java.util.Map;
import java.util.prefs.Preferences;

import org.vaadin.addons.logview.filter.FilterComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class LogViewComponent extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalSplitPanel split;

	@AutoGenerated
	private TabSheet tabSheet_1;

	@AutoGenerated
	private FilterComponent filter;

	@AutoGenerated
	private MenuBar menu;

	private final Preferences prefs = Preferences.userNodeForPackage(LogViewComponent.class).node("settings");

	public LogViewComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		createMenu();

		split.setSplitPosition(prefs.getInt("splitter.filter", 250), Sizeable.UNITS_PIXELS);
		split.setImmediate(true);
	}

	private void createMenu() {
		MenuItem file = menu.addItem("File", null);
		file.addItem("Save", saveCommand);
	}

	private final Command saveCommand = new Command() {
		@Override
		public void menuSelected(MenuItem selectedItem) {
			getWindow().showNotification("All changes are saved automatically!");
		}
	};

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// menu
		menu = new MenuBar();
		menu.setImmediate(false);
		menu.setWidth("100.0%");
		menu.setHeight("-1px");
		mainLayout.addComponent(menu);

		// split
		split = buildSplit();
		mainLayout.addComponent(split);
		mainLayout.setExpandRatio(split, 1.0f);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildSplit() {
		// common part: create layout
		split = new HorizontalSplitPanel() {
			@Override
			public void changeVariables(Object source, Map<String, Object> variables) {
				super.changeVariables(source, variables);
				prefs.putInt("splitter.filter", split.getSplitPosition());
			}
		};
		split.setImmediate(true);
		split.setWidth("100.0%");
		split.setHeight("100.0%");
		split.setMargin(false);

		// filter
		filter = new FilterComponent();
		filter.setImmediate(false);
		filter.setWidth("100.0%");
		filter.setHeight("100.0%");
		split.addComponent(filter);

		// tabSheet_1
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(false);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");
		split.addComponent(tabSheet_1);

		return split;
	}
}
