package org.vaadin.addons.logview.table;

import org.vaadin.addons.logview.Loader;

import com.github.logview.api.LogEntry;
import com.google.common.collect.ImmutableMap;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.Table.CellStyleGenerator;
import com.vaadin.ui.Table.ColumnReorderEvent;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class LogTable extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private transient Table table;

	private final transient static ImmutableMap<String, String> levels = new ImmutableMap.Builder<String, String>()
			.put("TRACE", "b666 ffff") //
			.put("DEBUG", "b036 ffff") //
			.put("INFO", "b360 ffff") //
			.put("WARN", "bc60 ffff") //
			.put("ERROR", "b900 ffff") //
			.put("FATAL", "bf00 ffff") //
			.build();

	public LogTable() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		final BeanItemContainer<DetailLogEntry> container = new BeanItemContainer<DetailLogEntry>(DetailLogEntry.class);
		int i = 0;
		for(LogEntry entry : Loader.entrys) {
			if(i > 1000) {
				break;
			}
			i++;
			container.addBean(new DetailLogEntry(entry));
		}

		// NDC Classname date id level message
		// table.setColumnCollapsed(ExampleUtil.iso3166_PROPERTY_FLAG, true);

		table.setCellStyleGenerator(new CellStyleGenerator() {
			@Override
			public String getStyle(Object itemId, Object propertyId) {
				if(propertyId == null) {
					if(itemId instanceof DetailLogEntry) {
						DetailLogEntry entry = (DetailLogEntry)itemId;
						String ret = levels.get(entry.getLevel());
						if(ret == null) {
							return ret;
						}
						return "cell " + ret;
					}
				}
				return null;
			}
		});
		table.addListener(new Table.ColumnReorderListener() {
			@Override
			public void columnReorder(ColumnReorderEvent event) {
				System.err.println("test: " + event);
			}
		});
		table.setContainerDataSource(container);

		TextField messageFilterField = new TextField();
		messageFilterField.addListener(new Property.ValueChangeListener() {
			@Override
			public void valueChange(ValueChangeEvent event) {
				String text = (String)event.getProperty().getValue();
				container.removeContainerFilters(DetailLogEntry.MESSAGE);
				if(text != null) {
					container.addContainerFilter(DetailLogEntry.MESSAGE, text, true, true);
				}
			}
		});
		table.setColumnHeader(DetailLogEntry.ID, "ID");
		table.setColumnHeader(DetailLogEntry.CLASS, "Class");
		table.setColumnHeader(DetailLogEntry.MESSAGE, "Message");
		table.setColumnHeader(DetailLogEntry.DATE, "Date");
		table.setColumnHeader(DetailLogEntry.LEVEL, "Level");
		table.setColumnCollapsed(DetailLogEntry.ID, true);
		// table.setColumnCollapsed(DetailLogEntry.LEVEL, true);
		table.setVisibleColumns(new Object[] {
			DetailLogEntry.ID,
			DetailLogEntry.DATE,
			DetailLogEntry.LEVEL,
			DetailLogEntry.NDC,
			DetailLogEntry.CLASS,
			DetailLogEntry.MESSAGE
		});
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// table
		table = new Table();
		table.setImmediate(true);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		table.setSelectable(true);
		table.setSortDisabled(true);
		table.setFooterVisible(true);
		table.setColumnReorderingAllowed(true);
		table.setColumnCollapsingAllowed(true);
		mainLayout.addComponent(table);

		return mainLayout;
	}
}
