package org.vaadin.addons.logview.table;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class LogTable extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private Table table;

	public LogTable() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// table
		table = new Table();
		table.setImmediate(true);
		table.setWidth("100.0%");
		table.setHeight("100.0%");
		table.setSelectable(true);
		table.setStyleName("iso3166");
		table.setColumnReorderingAllowed(true);
		table.setColumnCollapsingAllowed(true);
		mainLayout.addComponent(table);

		return mainLayout;
	}
}
