package org.vaadin.addons.logview;

import java.util.prefs.Preferences;

import org.vaadin.addons.logview.filter.FilterComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.Sizeable;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.MenuBar.Command;
import com.vaadin.ui.MenuBar.MenuItem;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class LogViewComponent extends CustomComponent {
	@AutoGenerated
	private VerticalLayout mainLayout;

	@AutoGenerated
	private HorizontalSplitPanel split;

	@AutoGenerated
	private TabSheet tabSheet_1;

	@AutoGenerated
	private Table table_1;

	@AutoGenerated
	private FilterComponent filter;

	@AutoGenerated
	private MenuBar menu;

	private final Preferences prefs = Preferences.userNodeForPackage(LogViewComponent.class).node("settings");

	public LogViewComponent() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		createMenu();

		split.setSplitPosition(prefs.getInt("splitter.filter", 250), Sizeable.UNITS_PIXELS);
	}

	private void createMenu() {
		MenuItem file = menu.addItem("Datei", null);
		file.addItem("Speichern", saveCommand);
		// file.addItem("Beenden", menuCommand);
	}

	private final Command saveCommand = new Command() {
		@Override
		public void menuSelected(MenuItem selectedItem) {
			prefs.putInt("splitter.filter", split.getSplitPosition());
			filter.save();
			getWindow().showNotification("Gespeichert!");
		}
	};

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// menu
		menu = new MenuBar();
		menu.setImmediate(false);
		menu.setWidth("100.0%");
		menu.setHeight("-1px");
		mainLayout.addComponent(menu);

		// split
		split = buildSplit();
		mainLayout.addComponent(split);
		mainLayout.setExpandRatio(split, 1.0f);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalSplitPanel buildSplit() {
		// common part: create layout
		split = new HorizontalSplitPanel();
		split.setImmediate(true);
		split.setWidth("100.0%");
		split.setHeight("100.0%");
		split.setMargin(false);

		// filter
		filter = new FilterComponent();
		filter.setImmediate(false);
		filter.setWidth("100.0%");
		filter.setHeight("100.0%");
		split.addComponent(filter);

		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		split.addComponent(tabSheet_1);

		return split;
	}

	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("100.0%");

		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("100.0%");
		tabSheet_1.addTab(table_1, "Tab", null);

		return tabSheet_1;
	}
}
